// Conductor (Chief of Staff). Narrates the day for Nur and routes work to the
// right specialist. For now it writes the morning/standing brief from the live
// snapshot + what the mesh did + what's waiting on her.
import { claude, claudeJSON } from "../anthropic";
import { humanize, withHumanSystem } from "../humanize";

export type BriefPoint = { text: string; href: string };

// Bullet-point brief with clickable destinations. Generated by the cron (cached),
// never on the render path. href must be one of the app's tabs.
export async function buildBriefPoints(ctx: {
  raisedMtd: string; raisedAll: string; donors: number; newMessages: number;
  pendingApprovals: number; openTasks: number; recentAgentActions: string[]; liveCampaigns: string[];
}): Promise<{ summary: string; points: BriefPoint[] } | null> {
  const system = withHumanSystem(`You are Sasa, Nisria's Chief-of-Staff AI. Write Nur a crisp, scannable brief as BULLET POINTS, not prose. 3-5 points, lead with what needs her. Each point is short (max ~12 words) and links to the most relevant screen.
Allowed href values ONLY: "/" (approvals/needs-you), "/inbox", "/donations", "/finance", "/tasks", "/content", "/agents", "/grants".
Return JSON: {"summary":"one short warm line","points":[{"text":"...","href":"/..."}]}`);
  const user = `Live: ${ctx.pendingApprovals} approvals waiting; ${ctx.newMessages} new messages; ${ctx.openTasks} open tasks; raised ${ctx.raisedMtd} this month (${ctx.raisedAll} all-time) from ${ctx.donors} donors; live campaigns: ${ctx.liveCampaigns.join(", ") || "none"}; agents recently: ${ctx.recentAgentActions.join("; ") || "quiet"}.`;
  const r = await claudeJSON<{ summary: string; points: BriefPoint[] }>(system, user, 500);
  if (!r) return null;
  // humanize gate: brief points are shown verbatim on the dashboard, so they must
  // never carry an em-dash or a placeholder (the founder's hard rule).
  return {
    summary: humanize(r.summary || ""),
    points: (r.points || []).map((p) => ({ href: p.href, text: humanize(p.text || "") })),
  };
}

export async function buildBrief(ctx: {
  raisedMtd: string;
  raisedAll: string;
  donors: number;
  newMessages: number;
  pendingApprovals: number;
  openTasks: number;
  recentAgentActions: string[];
  liveCampaigns: string[];
}): Promise<string> {
  const system = withHumanSystem(`You are Sasa, Nisria's Chief-of-Staff AI. Write a short, warm "here's where things stand" brief for Nur, the founder. 3-5 sentences max. Lead with what needs her, then what the agents handled, then one useful observation. Concrete, no fluff, no markdown headers. Address her as "you".`);
  const user = `Live state:
- Raised this month: ${ctx.raisedMtd} (all-time ${ctx.raisedAll})
- Donors: ${ctx.donors}
- New unread messages: ${ctx.newMessages}
- Items waiting on you (approvals): ${ctx.pendingApprovals}
- Open tasks: ${ctx.openTasks}
- Live campaigns: ${ctx.liveCampaigns.join("; ") || "none"}
- What the agents did recently: ${ctx.recentAgentActions.join("; ") || "nothing yet"}

Write the brief.`;
  try {
    return humanize(await claude(system, user, 320));
  } catch {
    // graceful fallback if Claude is unreachable
    const bits = [];
    if (ctx.pendingApprovals) bits.push(`${ctx.pendingApprovals} item${ctx.pendingApprovals > 1 ? "s" : ""} waiting on you`);
    if (ctx.newMessages) bits.push(`${ctx.newMessages} new message${ctx.newMessages > 1 ? "s" : ""}`);
    if (ctx.openTasks) bits.push(`${ctx.openTasks} open task${ctx.openTasks > 1 ? "s" : ""}`);
    return `Good day, Nur. ${bits.length ? bits.join(", ") + "." : "All quiet right now."} Raised ${ctx.raisedMtd} this month.`;
  }
}
